// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_login.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MsgLoginRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MsgLoginRoot : GPBRootObject
@end

#pragma mark - LoginRequestMsg

typedef GPB_ENUM(LoginRequestMsg_FieldNumber) {
  LoginRequestMsg_FieldNumber_PassWord = 1,
  LoginRequestMsg_FieldNumber_UserName = 2,
  LoginRequestMsg_FieldNumber_ApnsToken = 3,
  LoginRequestMsg_FieldNumber_ExtType = 4,
  LoginRequestMsg_FieldNumber_ExtLength = 5,
};

/**
 * LOGIN_REQUEST = 10000001
 **/
@interface LoginRequestMsg : GPBMessage

/** 密码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *passWord;
/** Test to see if @c passWord has been set. */
@property(nonatomic, readwrite) BOOL hasPassWord;

/** 发送方姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;
/** Test to see if @c userName has been set. */
@property(nonatomic, readwrite) BOOL hasUserName;

/** ios专用token字段，其他客户端不设置 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *apnsToken;
/** Test to see if @c apnsToken has been set. */
@property(nonatomic, readwrite) BOOL hasApnsToken;

/** 扩展类型 */
@property(nonatomic, readwrite) int64_t extType;

@property(nonatomic, readwrite) BOOL hasExtType;
/** 扩展消息体长度 */
@property(nonatomic, readwrite) int32_t extLength;

@property(nonatomic, readwrite) BOOL hasExtLength;
@end

#pragma mark - LoginResponseMsg

typedef GPB_ENUM(LoginResponseMsg_FieldNumber) {
  LoginResponseMsg_FieldNumber_Token = 1,
  LoginResponseMsg_FieldNumber_Uid = 2,
  LoginResponseMsg_FieldNumber_LastMsgId = 3,
};

/**
 * LOGIN_RESPONSE=20000001
 **/
@interface LoginResponseMsg : GPBMessage

/** 用户唯一标识符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/** Test to see if @c token has been set. */
@property(nonatomic, readwrite) BOOL hasToken;

/** 用户id */
@property(nonatomic, readwrite) int64_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
/** 服务器最后一次接收客户端发送消息id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *lastMsgId;
/** Test to see if @c lastMsgId has been set. */
@property(nonatomic, readwrite) BOOL hasLastMsgId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
