// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_logout.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MsgLogoutRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MsgLogoutRoot : GPBRootObject
@end

#pragma mark - LogoutRequestMsg

typedef GPB_ENUM(LogoutRequestMsg_FieldNumber) {
  LogoutRequestMsg_FieldNumber_ExtType = 1,
  LogoutRequestMsg_FieldNumber_ExtLength = 2,
};

/**
 * LOGOUT_REQUEST=10000011
 **/
@interface LogoutRequestMsg : GPBMessage

/** 扩展类型 */
@property(nonatomic, readwrite) int64_t extType;

@property(nonatomic, readwrite) BOOL hasExtType;
/** 扩展消息体长度 */
@property(nonatomic, readwrite) int32_t extLength;

@property(nonatomic, readwrite) BOOL hasExtLength;
@end

#pragma mark - LogoutResponseMsg

/**
 * LOGOUT_RESPONSE=20000011
 **/
@interface LogoutResponseMsg : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
