# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IMNetworking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'CocoaAsyncSocket'#长链接
  pod 'Protobuf'#数据序列化
  pod 'Realm'
end
