// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_statuscode.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "MsgStatuscodepbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MsgStatuscodeRoot

@implementation MsgStatuscodeRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - Enum StatusCode

GPBEnumDescriptor *StatusCode_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Success\000TokenInvalid\000UserNameAlreadyExit"
        "s\000Failed\000HaspendingCtrlMsg\000UserNamePassw"
        "ordError\000NotLogin\000UserHasOnlineInvalid\000";
    static const int32_t values[] = {
        StatusCode_Success,
        StatusCode_TokenInvalid,
        StatusCode_UserNameAlreadyExits,
        StatusCode_Failed,
        StatusCode_HaspendingCtrlMsg,
        StatusCode_UserNamePasswordError,
        StatusCode_NotLogin,
        StatusCode_UserHasOnlineInvalid,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(StatusCode)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:StatusCode_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL StatusCode_IsValidValue(int32_t value__) {
  switch (value__) {
    case StatusCode_Success:
    case StatusCode_TokenInvalid:
    case StatusCode_UserNameAlreadyExits:
    case StatusCode_Failed:
    case StatusCode_HaspendingCtrlMsg:
    case StatusCode_UserNamePasswordError:
    case StatusCode_NotLogin:
    case StatusCode_UserHasOnlineInvalid:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
