// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_type.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MessageGroup

/**
 * F000000（表明消息是请求类的，相应类的还是命令类的）
 * FFFFFF（具体消息类型）
 **/
typedef GPB_ENUM(MessageGroup) {
  /** 请求 */
  MessageGroup_Request = 10000000,

  /** 响应 */
  MessageGroup_Response = 20000000,

  /** 命令 */
  MessageGroup_Command = 30000000,
};

GPBEnumDescriptor *MessageGroup_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MessageGroup_IsValidValue(int32_t value);

#pragma mark - Enum MessageType

typedef GPB_ENUM(MessageType) {
  /** 登录请求 */
  MessageType_LoginRequest = 10000001,

  /** 登录结果 */
  MessageType_LoginResponse = 20000001,

  /** 获取离线消息 */
  MessageType_OfflinemessageRequest = 10000002,

  /** 反馈离线消息列表 */
  MessageType_OfflinemessageResponse = 20000002,

  /** 发送心跳 */
  MessageType_Heartbeat = 10000003,

  /** 心跳反馈 */
  MessageType_HeartbeatAck = 20000003,

  /** 关闭请求 */
  MessageType_CloseRequest = 10000004,

  /** 关闭反馈 */
  MessageType_CloseResponse = 20000004,

  /** 发送文本消息 */
  MessageType_ChatTextSend = 10000005,

  /** 发送图片消息 */
  MessageType_ChatImageSend = 10000006,

  /** 发送语音消息 */
  MessageType_ChatVoiceSend = 10000007,

  /** 聊天消息反馈 */
  MessageType_ChatAck = 20000005,

  /** 获取联系人列表 */
  MessageType_ContactsRequest = 10000008,

  /** 返回联系人列表 */
  MessageType_ContactsResponse = 20000008,

  /** 注册请求 */
  MessageType_RegistRequest = 10000009,

  /** 返回注册结果 */
  MessageType_RegistResponse = 20000009,

  /** 消息同步请求 */
  MessageType_MsgHandshakeRequest = 10000010,

  /** 消息同步结果 */
  MessageType_MsgHandshakeResponse = 20000010,

  /** 登出请求 */
  MessageType_LogoutRequest = 10000011,

  /** 登出结果 */
  MessageType_LogoutResponse = 20000011,

  /** 正在输入 */
  MessageType_TypingRequest = 10000012,

  /** 发送抖动通知 */
  MessageType_ShakeRequest = 10000013,

  /** 链路探测消息 */
  MessageType_DetectorRequest = 10000014,

  /** 链路探测应答消息 */
  MessageType_DetectorResponse = 20000014,
};

GPBEnumDescriptor *MessageType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MessageType_IsValidValue(int32_t value);

#pragma mark - MsgTypeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MsgTypeRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
