// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_shake.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "MsgShakepbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MsgShakeRoot

@implementation MsgShakeRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MsgShakeRoot_FileDescriptor

static GPBFileDescriptor *MsgShakeRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - ShakeRequestMsg

@implementation ShakeRequestMsg

@dynamic hasSenderUid, senderUid;
@dynamic hasReceiverUid, receiverUid;
@dynamic hasExtType, extType;
@dynamic hasExtLength, extLength;
@dynamic hasSenderName, senderName;

typedef struct ShakeRequestMsg__storage_ {
  uint32_t _has_storage_[1];
  int32_t extLength;
  NSString *senderName;
  int64_t senderUid;
  int64_t receiverUid;
  int64_t extType;
} ShakeRequestMsg__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "senderUid",
        .dataTypeSpecific.className = NULL,
        .number = ShakeRequestMsg_FieldNumber_SenderUid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ShakeRequestMsg__storage_, senderUid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "receiverUid",
        .dataTypeSpecific.className = NULL,
        .number = ShakeRequestMsg_FieldNumber_ReceiverUid,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ShakeRequestMsg__storage_, receiverUid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "extType",
        .dataTypeSpecific.className = NULL,
        .number = ShakeRequestMsg_FieldNumber_ExtType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ShakeRequestMsg__storage_, extType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "extLength",
        .dataTypeSpecific.className = NULL,
        .number = ShakeRequestMsg_FieldNumber_ExtLength,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ShakeRequestMsg__storage_, extLength),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "senderName",
        .dataTypeSpecific.className = NULL,
        .number = ShakeRequestMsg_FieldNumber_SenderName,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ShakeRequestMsg__storage_, senderName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ShakeRequestMsg class]
                                     rootClass:[MsgShakeRoot class]
                                          file:MsgShakeRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ShakeRequestMsg__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\005\001\t\000\002\013\000\003\007\000\004\t\000\005\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
