// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_chat.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MsgChatRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MsgChatRoot : GPBRootObject
@end

#pragma mark - ChatTextMsg

typedef GPB_ENUM(ChatTextMsg_FieldNumber) {
  ChatTextMsg_FieldNumber_SenderUid = 1,
  ChatTextMsg_FieldNumber_ReceiverUid = 2,
  ChatTextMsg_FieldNumber_Content = 3,
  ChatTextMsg_FieldNumber_ExtType = 4,
  ChatTextMsg_FieldNumber_ExtLength = 5,
  ChatTextMsg_FieldNumber_SenderName = 6,
};

/**
 * CHAT_TEXT_SEND=10000005
 **/
@interface ChatTextMsg : GPBMessage

/** 发送方 */
@property(nonatomic, readwrite) int64_t senderUid;

@property(nonatomic, readwrite) BOOL hasSenderUid;
/** 接收方 */
@property(nonatomic, readwrite) int64_t receiverUid;

@property(nonatomic, readwrite) BOOL hasReceiverUid;
/** 聊天内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

/** 扩展类型 */
@property(nonatomic, readwrite) int64_t extType;

@property(nonatomic, readwrite) BOOL hasExtType;
/** 扩展消息体长度 */
@property(nonatomic, readwrite) int32_t extLength;

@property(nonatomic, readwrite) BOOL hasExtLength;
/** 发送方姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *senderName;
/** Test to see if @c senderName has been set. */
@property(nonatomic, readwrite) BOOL hasSenderName;

@end

#pragma mark - ChatImageMsg

typedef GPB_ENUM(ChatImageMsg_FieldNumber) {
  ChatImageMsg_FieldNumber_SenderUid = 1,
  ChatImageMsg_FieldNumber_ReceiverUid = 2,
  ChatImageMsg_FieldNumber_OriginalURL = 3,
  ChatImageMsg_FieldNumber_ThumbURL = 4,
  ChatImageMsg_FieldNumber_Content = 5,
  ChatImageMsg_FieldNumber_ExtType = 6,
  ChatImageMsg_FieldNumber_ExtLength = 7,
  ChatImageMsg_FieldNumber_SenderName = 8,
};

/**
 * CHAT_IMAGE_SEND=10000006
 **/
@interface ChatImageMsg : GPBMessage

/** 发送方 */
@property(nonatomic, readwrite) int64_t senderUid;

@property(nonatomic, readwrite) BOOL hasSenderUid;
/** 接收方 */
@property(nonatomic, readwrite) int64_t receiverUid;

@property(nonatomic, readwrite) BOOL hasReceiverUid;
/** 原图片的url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *originalURL;
/** Test to see if @c originalURL has been set. */
@property(nonatomic, readwrite) BOOL hasOriginalURL;

/** 缩略图的url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *thumbURL;
/** Test to see if @c thumbURL has been set. */
@property(nonatomic, readwrite) BOOL hasThumbURL;

/** 缩略图内容base64 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/** Test to see if @c content has been set. */
@property(nonatomic, readwrite) BOOL hasContent;

/** 扩展类型 */
@property(nonatomic, readwrite) int64_t extType;

@property(nonatomic, readwrite) BOOL hasExtType;
/** 扩展消息体长度 */
@property(nonatomic, readwrite) int32_t extLength;

@property(nonatomic, readwrite) BOOL hasExtLength;
/** 发送方姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *senderName;
/** Test to see if @c senderName has been set. */
@property(nonatomic, readwrite) BOOL hasSenderName;

@end

#pragma mark - ChatVoiceMsg

typedef GPB_ENUM(ChatVoiceMsg_FieldNumber) {
  ChatVoiceMsg_FieldNumber_SenderUid = 1,
  ChatVoiceMsg_FieldNumber_ReceiverUid = 2,
  ChatVoiceMsg_FieldNumber_URL = 3,
  ChatVoiceMsg_FieldNumber_VoiceTime = 4,
  ChatVoiceMsg_FieldNumber_ExtType = 5,
  ChatVoiceMsg_FieldNumber_ExtLength = 6,
  ChatVoiceMsg_FieldNumber_SenderName = 7,
};

/**
 * CHAT_VOICE_SEND=10000007
 **/
@interface ChatVoiceMsg : GPBMessage

/** 发送方 */
@property(nonatomic, readwrite) int64_t senderUid;

@property(nonatomic, readwrite) BOOL hasSenderUid;
/** 接收方 */
@property(nonatomic, readwrite) int64_t receiverUid;

@property(nonatomic, readwrite) BOOL hasReceiverUid;
/** 语音的url */
@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

/** 语音时长 */
@property(nonatomic, readwrite) int32_t voiceTime;

@property(nonatomic, readwrite) BOOL hasVoiceTime;
/** 扩展类型 */
@property(nonatomic, readwrite) int64_t extType;

@property(nonatomic, readwrite) BOOL hasExtType;
/** 扩展消息体长度 */
@property(nonatomic, readwrite) int32_t extLength;

@property(nonatomic, readwrite) BOOL hasExtLength;
/** 发送方姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *senderName;
/** Test to see if @c senderName has been set. */
@property(nonatomic, readwrite) BOOL hasSenderName;

@end

#pragma mark - ChatAckMsg

typedef GPB_ENUM(ChatAckMsg_FieldNumber) {
  ChatAckMsg_FieldNumber_BodyExtType = 1,
  ChatAckMsg_FieldNumber_BodyExtLength = 2,
};

/**
 * CHAT_ACK=20000005
 **/
@interface ChatAckMsg : GPBMessage

/** 扩展类型, 如小秘书 */
@property(nonatomic, readwrite) int64_t bodyExtType;

@property(nonatomic, readwrite) BOOL hasBodyExtType;
/** 扩展长度 */
@property(nonatomic, readwrite) int32_t bodyExtLength;

@property(nonatomic, readwrite) BOOL hasBodyExtLength;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
