// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_statuscode.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum StatusCode

typedef GPB_ENUM(StatusCode) {
  /** 成功 */
  StatusCode_Success = 1,

  /** token失效 */
  StatusCode_TokenInvalid = 2,

  /** 用户名已经存在 */
  StatusCode_UserNameAlreadyExits = 3,

  /** 失败 */
  StatusCode_Failed = 4,

  /** 有正在处理的控制消息 */
  StatusCode_HaspendingCtrlMsg = 5,

  /** 用户名或密码错 */
  StatusCode_UserNamePasswordError = 6,

  /** 未登录 */
  StatusCode_NotLogin = 7,

  /** 用户在其他设备上已登录 */
  StatusCode_UserHasOnlineInvalid = 8,
};

GPBEnumDescriptor *StatusCode_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL StatusCode_IsValidValue(int32_t value);

#pragma mark - MsgStatuscodeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MsgStatuscodeRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
